# Generated by Django 4.0.6 on 2022-07-20 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stockmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Packet_Id', models.IntegerField()),
                ('Packet_Type', models.CharField(max_length=200)),
                ('Packet_content', models.CharField(max_length=200)),
                ('Calories', models.IntegerField()),
                ('Expiry_Date', models.CharField(max_length=200)),
                ('Quantity_in_Litres', models.IntegerField()),
            ],
        ),
    ]
