# Generated by Django 4.0.6 on 2022-07-21 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sun', '0002_alter_stockmodel_calories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmodel',
            name='Quantity_in_Litres',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
