# Generated by Django 4.0.6 on 2022-07-21 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sun', '0003_alter_stockmodel_quantity_in_litres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmodel',
            name='Calories',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stockmodel',
            name='Expiry_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stockmodel',
            name='Packet_Id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='stockmodel',
            name='Packet_Type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='stockmodel',
            name='Packet_content',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
