# Generated by Django 4.0.6 on 2022-08-09 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_name', models.CharField(max_length=200)),
                ('Product_Price', models.IntegerField()),
                ('Product_Image', models.ImageField(upload_to='')),
                ('product_Size', models.BooleanField()),
                ('Product_Description', models.TextField()),
            ],
        ),
    ]
