# Generated by Django 4.0.6 on 2022-08-09 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('priceapp', '0003_products_database_delete_products_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products_database',
            name='product_Size',
        ),
    ]
