# Generated by Django 4.0.6 on 2022-08-12 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('priceapp', '0004_remove_products_database_product_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products_database',
            name='Product_Image',
            field=models.ImageField(upload_to='images/%y'),
        ),
    ]
