# Generated by Django 4.0.6 on 2022-08-12 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('priceapp', '0005_alter_products_database_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products_database',
            name='id',
        ),
        migrations.AddField(
            model_name='products_database',
            name='Medium',
            field=models.BooleanField(default=False, primary_key='Large', serialize=False, verbose_name='Small'),
        ),
    ]
