# f=open("arun.txt","w+")
# f.write("I am arun\n")
# f.write("Bangalore")
# print(f)
# print(f.tell())
# f.seek(0)
# print(f.tell())
# print(f.read())

f=open('arun.txt',"w+")
f.write("pyspider\n")
f.write("Jspider\n")
print(f)
f.seek(0)
print(f.read())
f.seek(0)
print(f.readlines())
f.write("Qspider\n")
f.seek(0)
print(f.readlines())
l1=["arun\n","praveen\n","kiran\n",'giri']
f.writelines(l1)
f.seek(0)
print(f.read())
f.seek(0)
print(f.readlines())
f.seek(0)
l2=[]
for i in f:
    l2.append(i.strip('\n'))
print(l2)
