# Generated by Django 4.0.6 on 2022-07-23 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Creditos1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_id', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=100)),
                ('debe', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='std_model',
        ),
    ]
